server:
  http:
    addr: 0.0.0.0:8060
    timeout: 1s
  grpc:
    addr: 0.0.0.0:8080
    timeout: 1s
apollo:
  app_id: pay123456
  cluster: default
  endpoint: http://81.68.181.139:8080
  namespace: application
  secret: 45450aff807242e4b04e2618a5d5e984
