server:
  http:
    addr: 0.0.0.0:8060
    timeout: 1s
  grpc:
    addr: 0.0.0.0:8080
    timeout: 1s
apollo:
  app_id: sgxx1
  cluster: default
  endpoint: http://81.68.181.139:8080
  namespace: application,mysql,redis
  secret: 68b257a5cf2643438614f0c4e9750fe1
  backup_path: _autoGeneration/apollo
env: dev