server:
  http:
    addr: 0.0.0.0:8060
    timeout: 1s
  grpc:
    addr: 0.0.0.0:8080
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:root@tcp(127.0.0.1:3306)/test
  redis:
    addr: 192.168.1.4:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
    max_idle: 20
