server:
  http:
    addr: 0.0.0.0:8060
    timeout: 1s
  grpc:
    addr: 0.0.0.0:8080
    timeout: 1s
apollo:
  app_id: ms
  cluster: dev
  endpoint: http://192.168.1.5:8080
  namespace: application,mysql,redis
  secret: bbfbc03b62534917aa41d20337db2f9b
  backup_path: _autoGeneration/apollo
env: dev

